# Generated by Django 3.1.7 on 2021-06-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(max_length=10000, null=True, upload_to='measurements/static/images'),
        ),
    ]
